config/routes.rb
GroceryApp::Application.routes.draw do
  
  root 'groceries#index'

  resources :groceries


end

app/models/grocery.rb
class Grocery < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/groceries_controller.rb
class GroceriesController < ApplicationController

	def index
    @groceries = Grocery.all
  end

  def show
  	@grocery = Grocery.find(params[:id])
  end

  def new
  	@grocery = Grocery.new
  end

  def create
  	@grocery = Grocery.create grocery_params
  	redirect_to groceries_path(@grocery)
  end

  def edit
  	@grocery = Grocery.find(params[:id])
  end

  def update
  	@grocery = Grocery.find(params[:id])
  	@grocery.update grocery_params
  	redirect_to grocery_path(@grocery)
  end

  def destroy
  	Grocery.find(params[:id]).destroy
  	redirect_to root_path
  end

private
  def grocery_params
  	params.require(:grocery).permit(:item, :details)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groceries_helper.rb
module GroceriesHelper
end

app/views/groceries/edit.html.erb
<h1> Edit a Grocery List Item</h1>

<%= form_for @grocery do |f| %>

	<%= label_tag(:item, "Item:") %>
	<%= f.text_field :item %></br>

	<%= label_tag(:details, "Details:") %>
	<%= f.text_area :details %>

	<%= f.submit "Update" %>

<% end %>
</br>

	<%= link_to "Back to Grocery List", groceries_path %>

app/views/groceries/index.html.erb
<h2>Grocery List</h2>

<%= link_to "add item to the list", new_grocery_path %><br></br>
<% @groceries.each do |grocery| %>
	<li>
	<%= link_to grocery.item, grocery_path(grocery) %>
	<%=link_to "Edit", edit_grocery_path(grocery[:id])%> 
	<%=link_to "Delete", grocery, method: :delete, data: { confirm: "Your sure?" } %>
	</li>
<% end %>

app/views/groceries/new.html.erb
<h1> Add an Item</br> to the Grocery List </h1>

<%= form_for @grocery do |f| %>

		<%= label_tag(:item, "Item:") %>
		<%= f.text_field :item %></br>

		<%= label_tag(:details, "Details:") %>
		<%= f.text_area :details %></br>

		<%= f.submit "Add" %>

	<% end %>
	</br>

	<%= link_to "Back to Grocery List", groceries_path %>

app/views/groceries/show.html.erb
<h2>Grocery Details</h2>

<p>Item: <%= @grocery.item %></p><br></br>
<p>Details: <%= @grocery.details %><br></br>

<%= link_to "Back to Grocery List", groceries_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<div id="container">
		<div id="header">
			<head>
				<p>~Virtual Grocery List~</p>
					
  					<title>GroceryApp</title>
  					<link rel="stylesheet" type="text/css" href="/stylesheets/application.css" />
  					<%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  					<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  					<%= csrf_meta_tags %>
			</head>
		</div>
	<div id="body">
<body>
	<%= yield %>
</body>
	</div>
	<div id="footer">
		<p>Created by: Blair Cuny, WDI April 2014</p>
	</div>
	</div>
</html>